backend:
  name: git-gateway
  branch: main # သင့် GitHub branch အမည် (main သို့မဟုတ် master) ဖြစ်ကြောင်း သေချာပါစေ

media_folder: "static/images" # ဓာတ်ပုံတင်ရင် သိမ်းမယ့်နေရာ
public_folder: "/images"

collections:
  - name: "blog"
    label: "Upanna Posts"
    folder: "static/posts" # Blog စာသားဖိုင်တွေ သိမ်းမယ့်နေရာ
    create: true # Post အသစ်တိုးခွင့်ပြုသည်
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "ခေါင်းစဉ် (Title)", name: "title", widget: "string" }
      - { label: "အတန်း (Category)", name: "category", widget: "select", options: ["Diploma", "B.A", "M.A", "M.Phil", "Ph.D"] }
      - { label: "ရက်စွဲ (Date)", name: "date", widget: "datetime" }
      - { label: "ဓာတ်ပုံ (Featured Image)", name: "image", widget: "image", required: false }
      - { label: "စာသားများ (Body)", name: "body", widget: "markdown" }
